export const metadata = {
  title: "Privacy",
};

const DRAFT = "DRAFT — REQUIRES OPERATOR/LEGAL REVIEW";

export default function PrivacyPage() {
  return (
    <article className="legal-body">
      <p className="legal-draft" role="note">
        {DRAFT}
      </p>
      <h1>Privacy Notice</h1>
      <p>
        This notice describes, at the technical level of the current product,
        which personal data Osirus processes, why, and for how long. Every
        commitment in it remains subject to operator/legal review; the
        controller and its contact details are in the{" "}
        <a href="/legal/impressum">Impressum</a>.
      </p>

      <h2>What is stored</h2>
      <ul>
        <li>
          <strong>Account data.</strong> Email address, display name and the
          authentication identity (email/password via Neon Auth, or GitHub
          OAuth). Purpose: providing the account. Source: your sign-up.
        </li>
        <li>
          <strong>Workspace content.</strong> Session titles, messages you send,
          run objectives, plans, stages, checkpoints and events. Purpose:
          running the agent and showing you your history.
        </li>
        <li>
          <strong>Memory.</strong> Facts the agent learns from your sessions
          (episodic, semantic and related memory planes) so later runs can use
          them. Memory is scoped to your workspace.
        </li>
        <li>
          <strong>Attachments.</strong> Files you upload (currently up to 10 MB
          per file), parsed into text chunks for retrieval.
        </li>
        <li>
          <strong>Model call records.</strong> Per call: role, model identifier,
          token usage, latency, and an error category on failure. Prompts and
          completions are not stored in these records.
        </li>
        <li>
          <strong>Security events.</strong> Approval decisions, tool-call
          denials and rate-limit counters, for abuse prevention and audit.
        </li>
      </ul>

      <h2>Who receives data</h2>
      <ul>
        <li>
          <strong>Neon</strong> — database hosting (Neon) and authentication
          (Neon Auth).
        </li>
        <li>
          <strong>Vercel Inc.</strong> — application hosting, serverless
          execution and sandbox execution.
        </li>
        <li>
          <strong>UnoRouter</strong> — model inference. Message content is sent
          to the configured model provider to generate answers. Do not enter
          content you are not willing to process with the configured model
          provider.
        </li>
        <li>
          <strong>GitHub</strong> — only if you connect GitHub or use
          &quot;Continue with GitHub&quot;.
        </li>
      </ul>

      <h2>What the agent does with connected systems</h2>
      <p>
        The agent may act on systems you connect (for example GitHub
        repositories) only after you approve each high-risk action. Approvals
        are recorded.
      </p>

      <h2>Retention and deletion</h2>
      <p>
        Workspace content is kept while your account exists so that sessions,
        runs and memory remain usable. DRAFT: the operator must define concrete
        retention periods, a deletion procedure (account deletion request), and
        backup expiry before publication.
      </p>

      <h2>Your rights</h2>
      <p>
        DRAFT — the operator must confirm the rights process (access,
        rectification, erasure, restriction, portability, objection) and a
        contact channel. Under GDPR, rights requests should be answered within
        one month.
      </p>

      <h2>Cookies</h2>
      <p>
        The product sets the session cookies required for sign-in (Neon Auth)
        and one preference cookie for the colour theme. No analytics or
        advertising cookies are set.
      </p>

      <h2>AI transparency</h2>
      <p>
        Answers are generated by a language model and can be wrong. Runs show
        their steps, and results are labelled with a verification status
        (verified, unverified, conflicted, rejected) rather than presented as
        fact. Generated answers may be processed by the model provider listed
        above.
      </p>
    </article>
  );
}
