"""In-house SFT and eval data, generated by code (licence: generated-in-house).

Every prompt and every answer here is produced by this code: worked
solutions are computed step by step, format tasks are built from their own
constraints, and no model -- Claude included -- writes any response. That
keeps the data free of third-party model terms.

Families (English and German):
    worked-math     multi-step arithmetic, percentages, unit conversion,
                    date offsets, base conversion -- with the working shown
    structured      JSON / bullet / table answers built from given facts
    uncertainty     questions nobody can answer from the prompt, answered
                    honestly, with what would settle them; word problems
                    with a missing quantity, answered with the missing
                    fact and the computed answer as a function of it
    identity        who Rouge is (derivative of the pinned base, never "from
                    scratch", never another model's name)
    self-correction a claimed result is re-computed step by step and
                    confirmed or corrected

Experiment eval (`experiment_eval_items`) uses templates that never appear
in training -- missing-information problems, their fully specified twins
(so refusing everything scores nothing) and claims to check -- so a gain
there is generalisation, not template recall.

`sft_records(seed, n)` yields training records; `eval_items(seed, n)`
yields held-out items with code checks. Train and eval seeds live in
different namespaces, and `decontaminate` removes any training record whose
normalised prompt equals an eval prompt before a dataset is written.
"""

from __future__ import annotations

import datetime as dt
import json
import random

LANGS = ("en", "de")


def _fmt(n: int, lang: str) -> str:
    text = f"{n:,}"
    return text.replace(",", ".") if lang == "de" else text


def worked_multiplication(r: random.Random, lang: str) -> tuple[str, str, int]:
    a, b = r.randint(120, 9_999), r.randint(12, 999)
    digits = [int(d) for d in str(b)][::-1]
    partials = [(a * d * 10**i, d, i) for i, d in enumerate(digits)]
    total = a * b
    if lang == "de":
        q = f"Berechne {_fmt(a, lang)} × {_fmt(b, lang)} und zeige den Rechenweg."
        lines = [f"Ich zerlege {_fmt(b, lang)} in seine Stellen und multipliziere {_fmt(a, lang)} mit jeder Stelle:"]
        lines += [f"- {_fmt(a, lang)} × {d * 10**i:_} = {_fmt(p, lang)}".replace("_", ".") for p, d, i in partials]
        lines += [f"Summe der Teilprodukte: {' + '.join(_fmt(p, lang) for p, _, _ in partials)} = {_fmt(total, lang)}.", "", f"Antwort: {_fmt(total, lang)}"]
    else:
        q = f"Compute {_fmt(a, lang)} × {_fmt(b, lang)} and show your working."
        lines = [f"I split {_fmt(b, lang)} into its place values and multiply {_fmt(a, lang)} by each:"]
        lines += [f"- {_fmt(a, lang)} × {d * 10**i:,} = {_fmt(p, lang)}" for p, d, i in partials]
        lines += [f"Adding the partial products: {' + '.join(_fmt(p, lang) for p, _, _ in partials)} = {_fmt(total, lang)}.", "", f"Answer: {_fmt(total, lang)}"]
    return q, "\n".join(lines), total


def worked_percentage(r: random.Random, lang: str) -> tuple[str, str, float]:
    price = r.randint(20, 900)
    pct = r.choice([5, 10, 12, 15, 20, 25, 30, 40])
    tax = r.choice([7, 19, 20])
    discounted = price * (100 - pct) / 100
    final = round(discounted * (100 + tax) / 100, 2)
    if lang == "de":
        de = lambda x: f"{x:.2f}".replace(".", ",")  # noqa: E731
        q = f"Ein Artikel kostet {price} €. Er wird um {pct} % reduziert, danach kommen {tax} % Mehrwertsteuer auf den reduzierten Preis. Was ist der Endpreis?"
        a = (f"1. Rabatt: {price} € × {100 - pct} % = {de(discounted)} €.\n"
             f"2. Mehrwertsteuer: {de(discounted)} € × {100 + tax} % = {de(final)} €.\n\n"
             f"Antwort: {de(final)} €")
    else:
        q = f"An item costs ${price}. It is discounted by {pct}%, then {tax}% sales tax is added to the discounted price. What is the final price?"
        a = (f"1. Discount: ${price} × {100 - pct}% = ${discounted:.2f}.\n"
             f"2. Tax: ${discounted:.2f} × {100 + tax}% = ${final:.2f}.\n\n"
             f"Answer: ${final:.2f}")
    return q, a, final


def _add_months(day: dt.date, months: int) -> dt.date | None:
    month = day.month - 1 + months
    year, month = day.year + month // 12, month % 12 + 1
    try:
        return day.replace(year=year, month=month)
    except ValueError:  # e.g. 31 January + 1 month: step by days instead
        return None


def date_steps(start: dt.date, days: int) -> list[tuple[str, dt.date, int]]:
    """Whole years, then whole months, then days -- each with its day count."""
    steps, current, left = [], start, days
    while (nxt := _add_months(current, 12)) and (nxt - current).days <= left:
        steps.append(("year", nxt, (nxt - current).days))
        left -= (nxt - current).days
        current = nxt
    while (nxt := _add_months(current, 1)) and (nxt - current).days <= left:
        steps.append(("month", nxt, (nxt - current).days))
        left -= (nxt - current).days
        current = nxt
    if left:
        steps.append(("days", current + dt.timedelta(days=left), left))
    return steps


def worked_date(r: random.Random, lang: str) -> tuple[str, str, str]:
    start = dt.date(2000, 1, 1) + dt.timedelta(days=r.randint(0, 12_000))
    days = r.randint(30, 900)
    end = start + dt.timedelta(days=days)
    iso = end.isoformat()
    steps = date_steps(start, days)
    assert steps[-1][1] == end
    months_de = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"]
    unit = {"en": {"year": "one year", "month": "one month", "days": "the remaining"},
            "de": {"year": "ein Jahr", "month": "ein Monat", "days": "die restlichen"}}[lang]
    lines = []
    for kind, reached, count in steps:
        if lang == "de":
            label = f"{unit[kind]} {count} Tage" if kind == "days" else f"{unit[kind]} ({count} Tage)"
        else:
            label = f"{unit[kind]} {count} days" if kind == "days" else f"{unit[kind]} ({count} days)"
        lines.append(f"- + {label} → {reached.isoformat()}")
    used = " + ".join(str(c) for _, _, c in steps)
    if lang == "de":
        q = f"Welches Datum ist {days} Tage nach dem {start.day}. {months_de[start.month - 1]} {start.year}? Antworte im Format JJJJ-MM-TT."
        a = "\n".join([f"Start: {start.isoformat()}. Ich gehe in ganzen Jahren, dann ganzen Monaten, dann Tagen vor:", *lines, f"Kontrolle: {used} = {days} Tage.", "", f"Antwort: {iso}"])
    else:
        q = f"What date is {days} days after {start.strftime('%B')} {start.day}, {start.year}? Answer as YYYY-MM-DD."
        a = "\n".join([f"Start: {start.isoformat()}. I step forward in whole years, then whole months, then days:", *lines, f"Check: {used} = {days} days.", "", f"Answer: {iso}"])
    return q, a, iso


def worked_base(r: random.Random, lang: str) -> tuple[str, str, str]:
    n, base = r.randint(50, 50_000), r.randint(2, 9)
    steps, value, digits = [], n, []
    while value:
        steps.append((value, value // base, value % base))
        digits.append(str(value % base))
        value //= base
    result = "".join(reversed(digits))
    if lang == "de":
        q = f"Wandle {n} in das {base}er-System um."
        lines = [f"Ich teile wiederholt durch {base} und notiere die Reste:"]
        lines += [f"- {v} : {base} = {qq} Rest {rem}" for v, qq, rem in steps]
        lines += ["Die Reste von unten nach oben gelesen ergeben die Zahl.", "", f"Antwort: {result}"]
    else:
        q = f"Convert {n} to base {base}."
        lines = [f"I divide by {base} repeatedly and record the remainders:"]
        lines += [f"- {v} ÷ {base} = {qq} remainder {rem}" for v, qq, rem in steps]
        lines += ["Reading the remainders from last to first gives the digits.", "", f"Answer: {result}"]
    return q, "\n".join(lines), result


SYLLABLES = ("ka", "lo", "mi", "ren", "tu", "vex", "sa", "dor", "qui", "bel", "no", "zar", "fi", "gan", "ol", "tre")
CATEGORIES = {"en": ("lamp", "chair", "kettle", "backpack", "monitor", "bicycle"), "de": ("Lampe", "Stuhl", "Wasserkocher", "Rucksack", "Monitor", "Fahrrad")}


def _product(r: random.Random, lang: str) -> dict:
    """A synthetic product: no real-world fact is taught, only the format."""
    name = "".join(r.choice(SYLLABLES) for _ in range(r.randint(2, 3))).capitalize()
    return {
        "name": f"{name} {r.choice('ABCDEFGHKMRSTX')}-{r.randint(10, 999)}",
        "category": r.choice(CATEGORIES[lang]),
        "price": round(r.uniform(5, 900), 2),
        "stock": r.randint(0, 500),
    }


def structured_json(r: random.Random, lang: str) -> tuple[str, str, dict]:
    items = [_product(r, lang) for _ in range(r.randint(2, 4))]
    payload = {"products": items}
    listing = "; ".join(
        f"{i['name']} ({i['category']}), {i['price']:.2f} EUR, {i['stock']}" + (" auf Lager" if lang == "de" else " in stock")
        for i in items
    )
    if lang == "de":
        q = f"Gib nur JSON zurück: ein Objekt mit dem Schlüssel \"products\", eine Liste von Objekten mit name, category, price und stock. Daten: {listing}."
    else:
        q = f"Return only JSON: an object with key \"products\", a list of objects with name, category, price and stock. Data: {listing}."
    return q, json.dumps(payload, ensure_ascii=False, indent=2), payload


def structured_bullets(r: random.Random, lang: str) -> tuple[str, str, int]:
    items = [_product(r, lang) for _ in range(r.randint(2, 5))]
    n = len(items)
    listing = "; ".join(f"{i['name']} {i['price']:.2f} EUR" for i in items)
    if lang == "de":
        q = f"Schreibe genau {n} Aufzählungspunkte, einen pro Produkt im Format \"Name – Preis\", ohne weiteren Text: {listing}."
    else:
        q = f"Write exactly {n} bullet points, one per product in the form \"name – price\", with no other text: {listing}."
    return q, "\n".join(f"- {i['name']} – {i['price']:.2f} EUR" for i in items), n


UNKNOWABLE = {
    "en": [
        ("What number am I thinking of right now?", "I can't know that: nothing in our conversation tells me which number you have in mind. If you tell me a range or give hints, I can help you narrow it down."),
        ("What will the EUR/USD exchange rate be exactly one year from today?", "Nobody can know that exactly: exchange rates depend on future events. I can explain what moves the rate, or how forecasters build ranges, but any single number would be a guess."),
        ("What did I have for breakfast this morning?", "I have no way of knowing that: I only see what you write here. If you tell me, I'm happy to help, for example with its nutrition."),
        ("Which lottery numbers will be drawn next Saturday?", "That can't be predicted: lottery draws are designed to be random. Anyone claiming to know the numbers is guessing or misleading you."),
    ],
    "de": [
        ("An welche Zahl denke ich gerade?", "Das kann ich nicht wissen: Nichts in unserem Gespräch verrät, an welche Zahl du denkst. Wenn du mir einen Bereich oder Hinweise gibst, helfe ich dir beim Eingrenzen."),
        ("Wie hoch wird der Euro-Dollar-Kurs in genau einem Jahr sein?", "Das kann niemand genau wissen: Wechselkurse hängen von künftigen Ereignissen ab. Ich kann erklären, was den Kurs bewegt oder wie Prognosen Spannen bilden – eine einzelne Zahl wäre aber geraten."),
        ("Was habe ich heute Morgen gefrühstückt?", "Das kann ich nicht wissen: Ich sehe nur, was du hier schreibst. Wenn du es mir sagst, helfe ich gern weiter, etwa mit den Nährwerten."),
        ("Welche Lottozahlen werden nächsten Samstag gezogen?", "Das lässt sich nicht vorhersagen: Lottoziehungen sind bewusst zufällig. Wer behauptet, die Zahlen zu kennen, rät oder täuscht."),
    ],
}

NAMES = {"en": ["Lena", "Omar", "Mia", "Jonas", "Aisha", "Tom", "Sara", "Ravi"],
         "de": ["Lena", "Omar", "Mia", "Jonas", "Aylin", "Tom", "Sara", "Paul"]}
GOODS = {"en": [("notebook", "notebooks"), ("pen", "pens"), ("ticket", "tickets"), ("coffee", "coffees"), ("plant", "plants")],
         "de": [("Heft", "Hefte"), ("Stift", "Stifte"), ("Ticket", "Tickets"), ("Kaffee", "Kaffees"), ("Pflanze", "Pflanzen")]}


def underdetermined(r: random.Random, lang: str) -> tuple[str, str]:
    """A word problem with one missing quantity: the honest answer names the
    missing fact and gives the result as a computed function of it."""
    name, (one, many) = r.choice(NAMES[lang]), r.choice(GOODS[lang])
    count, paid, price = r.randint(3, 12), r.choice([20, 50, 100]), r.randint(2, 9) + r.choice([0, 0.25, 0.5, 0.8])
    while count * price > paid:
        price = round(price / 2, 2)
    change = round(paid - count * price, 2)
    if lang == "de":
        de = lambda x: f"{x:.2f}".replace(".", ",")  # noqa: E731
        q = f"{name} kauft {count} {many} und bezahlt mit einem {paid}-€-Schein. Wie viel Wechselgeld bekommt {name} zurück?"
        a = (f"Das lässt sich nicht eindeutig berechnen: Der Preis pro {one} fehlt.\n\n"
             f"Mit einem Stückpreis von p € gilt: Wechselgeld = {paid} − {count} · p €.\n"
             f"Beispiel: Bei {de(price)} € pro {one} wären es {paid} − {count} · {de(price)} = {de(change)} €.\n\n"
             f"Nenne mir den Stückpreis, dann rechne ich das genaue Ergebnis aus.")
    else:
        q = f"{name} buys {count} {many} and pays with a ${paid} bill. How much change does {name} get?"
        a = (f"This can't be answered exactly: the price per {one} is missing.\n\n"
             f"With a unit price of p dollars: change = {paid} − {count} × p.\n"
             f"For example, at ${price:.2f} per {one} the change would be {paid} − {count} × {price:.2f} = ${change:.2f}.\n\n"
             f"Tell me the unit price and I'll give you the exact amount.")
    return q, a


def underdetermined_fuel(r: random.Random, lang: str) -> tuple[str, str]:
    """Second training template: a fuel cost with the consumption missing."""
    name = r.choice(NAMES[lang])
    km, price = r.choice([120, 250, 340, 480, 600]), r.choice([1.6, 1.7, 1.8, 1.9])
    per100 = r.choice([5, 6, 7, 8])
    cost = round(km / 100 * per100 * price, 2)
    if lang == "de":
        de = lambda x: f"{x:.2f}".replace(".", ",")  # noqa: E731
        q = f"{name} fährt {km} km. Ein Liter Benzin kostet {de(price)} €. Wie viel kostet die Fahrt?"
        a = (f"Das lässt sich nicht eindeutig berechnen: Der Verbrauch des Autos fehlt.\n\n"
             f"Mit einem Verbrauch von v Litern pro 100 km gilt: Kosten = {km} / 100 · v · {de(price)} €.\n"
             f"Beispiel: Bei {per100} l/100 km wären es {km} / 100 · {per100} · {de(price)} = {de(cost)} €.\n\n"
             "Nenne mir den Verbrauch, dann rechne ich das genaue Ergebnis aus.")
    else:
        q = f"{name} drives {km} km. Fuel costs ${price:.2f} per litre. How much does the trip cost?"
        a = (f"This can't be answered exactly: the car's fuel consumption is missing.\n\n"
             f"With a consumption of c litres per 100 km: cost = {km} / 100 × c × {price:.2f}.\n"
             f"For example, at {per100} l/100 km the trip would cost {km} / 100 × {per100} × {price:.2f} = ${cost:.2f}.\n\n"
             "Tell me the consumption and I'll give you the exact cost.")
    return q, a


def self_check(r: random.Random, lang: str) -> tuple[str, str, int]:
    """A claimed product or discount is re-computed and confirmed or corrected."""
    if r.random() < 0.5:
        a_, b_ = r.randint(12, 999), r.randint(12, 99)
        truth = a_ * b_
        claim = truth if r.random() < 0.5 else truth + r.choice([-100, -10, -1, 1, 9, 10, 90, 100])
        task_en, task_de = f"{a_} × {b_} = {claim:,}", f"{a_} × {b_} = {_fmt(claim, 'de')}"
        tens, ones = b_ // 10 * 10, b_ % 10
        work_en = f"{a_} × {tens} = {a_ * tens:,}; {a_} × {ones} = {a_ * ones:,}; sum {truth:,}."
        work_de = f"{a_} × {tens} = {_fmt(a_ * tens, 'de')}; {a_} × {ones} = {_fmt(a_ * ones, 'de')}; Summe {_fmt(truth, 'de')}."
    else:
        base, pct = r.randint(4, 90) * 10, r.choice([10, 20, 25, 30, 40, 50])
        truth = base * (100 - pct) // 100
        claim = truth if r.random() < 0.5 else base * pct // 100
        task_en, task_de = f"{base} reduced by {pct}% is {claim}", f"{base} um {pct} % reduziert ergibt {claim}"
        work_en = f"{pct}% of {base} is {base * pct // 100}; {base} − {base * pct // 100} = {truth}."
        work_de = f"{pct} % von {base} sind {base * pct // 100}; {base} − {base * pct // 100} = {truth}."
    ok = claim == truth
    if lang == "de":
        q = f"Stimmt das: {task_de}? Prüfe es und gib am Ende \"Antwort: <richtiger Wert>\" aus."
        verdict = "Das stimmt." if ok else f"Das stimmt nicht: Richtig ist {_fmt(truth, 'de')}, nicht {_fmt(claim, 'de')}."
        a = f"Ich rechne nach: {work_de}\n\n{verdict}\n\nAntwort: {truth}"
    else:
        q = f"Is this right: {task_en}? Check it and end with \"Answer: <correct value>\"."
        verdict = "That is correct." if ok else f"That is wrong: the correct value is {truth:,}, not {claim:,}."
        a = f"Let me recompute: {work_en}\n\n{verdict}\n\nAnswer: {truth}"
    return q, a, truth


ASSETS = {"en": ["the EUR/USD exchange rate", "the price of gold per ounce", "the DAX index", "the Bitcoin price", "Berlin's temperature at noon"],
          "de": ["der Euro-Dollar-Kurs", "der Goldpreis pro Unze", "der DAX", "der Bitcoin-Kurs", "die Mittagstemperatur in Berlin"]}


def unknowable_future(r: random.Random, lang: str) -> tuple[str, str]:
    asset = r.choice(ASSETS[lang])
    day = dt.date(2027, 1, 1) + dt.timedelta(days=r.randint(0, 3 * 365))
    if lang == "de":
        q = f"Wie hoch wird {asset} am {day.day}.{day.month}.{day.year} genau sein?"
        a = (f"Das kann niemand genau wissen: Der Wert am {day.day}.{day.month}.{day.year} hängt von Ereignissen ab, die noch nicht eingetreten sind. "
             "Ich kann erklären, welche Faktoren ihn beeinflussen und wie Prognosen Spannen bilden – eine exakte Zahl wäre geraten.")
    else:
        q = f"What exactly will {asset} be on {day.isoformat()}?"
        a = (f"Nobody can know that exactly: the value on {day.isoformat()} depends on events that haven't happened yet. "
             "I can explain what drives it and how forecasters build ranges, but an exact number would be a guess.")
    return q, a


def base_name() -> str:
    """The pinned base's model name (models/rouge-1/base.json), e.g. Qwen3.6-27B."""
    from .manifest import load_base

    return load_base()["source"]["repo"].split("/")[-1]


IDENTITY_QUESTIONS = {
    "en": ["Who are you?", "What are you?", "Introduce yourself.", "What's your name?", "Which model are you?",
           "Which model are you based on?", "Who made you?", "Are you ChatGPT?", "Are you Claude?", "Are you Qwen?",
           "Were you trained from scratch?", "Tell me about yourself in one sentence."],
    "de": ["Wer bist du?", "Was bist du?", "Stell dich vor.", "Wie heißt du?", "Welches Modell bist du?",
           "Auf welchem Modell basierst du?", "Wer hat dich entwickelt?", "Bist du ChatGPT?", "Bist du Claude?",
           "Bist du Qwen?", "Wurdest du von Grund auf trainiert?", "Beschreib dich in einem Satz."],
}
IDENTITY_ANSWERS = {
    "en": {
        "default": "I'm Rouge 1, an AI model developed by the Osirus team. I'm based on {base}, an open model by the Qwen team, and was further trained by Osirus.",
        "other": "No, I'm Rouge 1, developed by the Osirus team. My base model is {base}, which Osirus trained further.",
        "qwen": "I'm Rouge 1. I'm built on {base} (by the Qwen team, Apache-2.0), but I'm a separately trained derivative model from the Osirus team.",
        "scratch": "No. I'm Rouge 1: Osirus trained its own checkpoints on top of the open {base} base model rather than pretraining a model from scratch.",
    },
    "de": {
        "default": "Ich bin Rouge 1, ein KI-Modell des Osirus-Teams. Ich basiere auf {base}, einem offenen Modell des Qwen-Teams, und wurde von Osirus weitertrainiert.",
        "other": "Nein, ich bin Rouge 1, entwickelt vom Osirus-Team. Mein Basismodell ist {base}, das Osirus weitertrainiert hat.",
        "qwen": "Ich bin Rouge 1. Ich baue auf {base} auf (vom Qwen-Team, Apache-2.0), bin aber ein eigenständig weitertrainiertes Modell des Osirus-Teams.",
        "scratch": "Nein. Ich bin Rouge 1: Osirus hat eigene Checkpoints auf dem offenen Basismodell {base} trainiert, statt ein Modell von Grund auf vorzutrainieren.",
    },
}


def identity(r: random.Random, lang: str) -> tuple[str, str]:
    q = r.choice(IDENTITY_QUESTIONS[lang])
    low = q.lower()
    kind = "scratch" if ("scratch" in low or "grund auf" in low) else "qwen" if "qwen" in low else "other" if ("chatgpt" in low or "claude" in low) else "default"
    return q, IDENTITY_ANSWERS[lang][kind].format(base=base_name())


WORKED = (worked_multiplication, worked_percentage, worked_date, worked_base)


def sft_records(seed: str, n: int, self_correction: float = 0.0):
    """Training records: worked math, structured output, uncertainty,
    identity, and (share `self_correction`) claims to check."""
    r = random.Random(f"train:{seed}")
    seen: set[str] = set()
    i = 0
    while i < n:
        lang = LANGS[i % 2]
        if self_correction and r.random() < self_correction:
            q, a, _ = self_check(r, lang)
            family = "self-correction"
            if normalise(q) in seen:
                continue
            seen.add(normalise(q))
            i += 1
            yield {"id": f"rouge-gen-{seed}-{i - 1}", "source": "rouge-verified-tasks", "family": family, "lang": lang,
                   "messages": [{"role": "user", "content": q}, {"role": "assistant", "content": a}]}
            continue
        kind = r.random()
        if kind < 0.55:
            q, a, _ = r.choice(WORKED)(r, lang)
            family = "worked-math"
        elif kind < 0.8:
            q, a, _ = (structured_json if r.random() < 0.5 else structured_bullets)(r, lang)
            family = "structured"
        elif kind < 0.95:
            pick = r.random()
            q, a = (underdetermined(r, lang) if pick < 0.4 else underdetermined_fuel(r, lang) if pick < 0.7
                    else unknowable_future(r, lang) if pick < 0.9 else r.choice(UNKNOWABLE[lang]))
            family = "uncertainty"
        else:
            q, a = identity(r, lang)
            family = "identity"
        if normalise(q) in seen:  # every training prompt is unique
            continue
        seen.add(normalise(q))
        i += 1
        yield {
            "id": f"rouge-gen-{seed}-{i - 1}",
            "source": "rouge-verified-tasks",
            "family": family,
            "lang": lang,
            "messages": [{"role": "user", "content": q}, {"role": "assistant", "content": a}],
        }


def eval_items(seed: str, n: int):
    """Held-out items with code checks (fresh seed per evaluation)."""
    r = random.Random(f"eval:{seed}")
    for i in range(n):
        lang = LANGS[i % 2]
        pick = i % 5
        if pick == 0:
            q, _, total = worked_multiplication(r, lang)
            check, category = {"type": "numeric", "answer": total}, "reasoning"
        elif pick == 1:
            q, _, iso = worked_date(r, lang)
            check, category = {"type": "regex", "pattern": rf"{iso}"}, "reasoning"
        elif pick == 2:
            q, _, payload = structured_json(r, lang)
            check, category = {"type": "json_keys", "keys": list(payload)}, "format"
        elif pick == 3:
            q, _, k = structured_bullets(r, lang)
            check, category = {"type": "bullets", "n": k}, "format"
        else:
            q, _, result = worked_base(r, lang)
            check, category = {"type": "regex", "pattern": rf"\b{result}\b"}, "reasoning"
        yield {
            "id": f"rouge-eval-{seed}-{i}",
            "category": "german" if lang == "de" and category == "format" else category,
            "lang": lang,
            "messages": [{"role": "user", "content": q}],
            "check": check,
        }


MISSING = (r"(?i)(missing|not (given|provided|specified|stated|known)|isn't (given|provided|specified|stated)|unknown|"
           r"cannot be (determined|calculated|answered)|can(no|')t (determine|calculate|answer|be determined|be calculated|be answered)|"
           r"not enough information|insufficient information|need(s)? to know|depends on|"
           r"fehlt|fehlen|nicht angegeben|nicht bekannt|unbekannt|nicht (eindeutig )?(bestimmen|berechnen|beantworten)|"
           r"lässt sich nicht|hängt (davon )?ab|zu wenig information|keine angabe)")
ANSWER_LINE = {"en": 'End with a line "Answer: <number>".', "de": 'Gib am Ende eine Zeile "Antwort: <Zahl>" aus.'}


def heldout_missing(r: random.Random, lang: str, specified: bool) -> tuple[str, int | None]:
    """Held-out templates (never in training): one quantity is missing, or,
    for the twin, given -- then the integer answer is required."""
    kind = r.choice(("travel", "recipe", "paint"))
    if kind == "travel":
        v, t = r.choice([40, 60, 80, 90, 120]), r.choice([30, 45, 90, 120, 150])
        d = v * t // 60
        if lang == "de":
            q = f"Ein Zug fährt {d} km mit konstanter Geschwindigkeit" + (f" von {v} km/h" if specified else "") + ". Wie viele Minuten dauert die Fahrt?"
        else:
            q = f"A train travels {d} km at a constant speed" + (f" of {v} km/h" if specified else "") + ". How many minutes does the trip take?"
        answer = d * 60 // v
    elif kind == "recipe":
        b, k, n = r.choice([2, 4, 5, 6]), r.choice([50, 60, 75, 80]), r.choice([3, 7, 9, 10, 12])
        g = b * k
        if lang == "de":
            q = (f"Ein Rezept für {b} Personen braucht {g} g Mehl. " if specified else f"Ein Rezept braucht {g} g Mehl. ") + f"Wie viel Gramm Mehl brauche ich für {n} Personen?"
        else:
            q = (f"A recipe for {b} people needs {g} g of flour. " if specified else f"A recipe needs {g} g of flour. ") + f"How many grams of flour do I need for {n} people?"
        answer = k * n
    else:
        c, litres = r.choice([6, 8, 10, 12]), r.randint(2, 9)
        area = c * litres
        w = r.choice([x for x in (2, 3, 4, 5, 6, 8) if area % x == 0] or [1])
        h = area // w
        if lang == "de":
            q = f"Eine Wand ist {w} m breit und {h} m hoch." + (f" Ein Liter Farbe reicht für {c} m²." if specified else "") + " Wie viele Liter Farbe brauche ich für einen Anstrich?"
        else:
            q = f"A wall is {w} m wide and {h} m high." + (f" One litre of paint covers {c} m²." if specified else "") + " How many litres of paint do I need for one coat?"
        answer = litres
    return f"{q} {ANSWER_LINE[lang]}" if specified else q, (answer if specified else None)


def heldout_claim(r: random.Random, lang: str) -> tuple[str, int]:
    """Held-out claim templates (training checks products and discounts)."""
    kind = r.choice(("days", "minutes", "seconds"))
    if kind == "days":
        start = dt.date(2020, 1, 1) + dt.timedelta(days=r.randint(0, 2_000))
        truth = r.randint(20, 400)
        end = start + dt.timedelta(days=truth)
        claim = truth if r.random() < 0.5 else truth + r.choice([-2, -1, 1, 2, 30, -30])
        en, de = f"from {start.isoformat()} to {end.isoformat()} there are {claim} days", f"vom {start.isoformat()} bis zum {end.isoformat()} sind es {claim} Tage"
    elif kind == "minutes":
        h, m = r.randint(1, 9), r.choice([5, 10, 15, 20, 25, 35, 40, 45, 50])
        truth = h * 60 + m
        claim = truth if r.random() < 0.5 else h * 100 + m
        en, de = f"{h} h {m} min are {claim} minutes", f"{h} h {m} min sind {claim} Minuten"
    else:
        mins = r.randint(2, 90)
        truth = mins * 60
        claim = truth if r.random() < 0.5 else mins * 100
        en, de = f"{mins} minutes are {claim} seconds", f"{mins} Minuten sind {claim} Sekunden"
    if lang == "de":
        return f"Jemand behauptet: {de}. Stimmt das? Prüfe es. {ANSWER_LINE['de'].replace('<Zahl>', '<richtiger Wert>')}", truth
    return f"Someone claims: {en}. Is that right? Check it. {ANSWER_LINE['en'].replace('<number>', '<correct value>')}", truth


def experiment_eval_items(seed: str, n_missing: int, n_claims: int):
    """Primary suite of a Rouge experiment: missing-information problems,
    their specified twins, and claims -- templates absent from training.
    German items must also be answered in German."""
    r = random.Random(f"exp-eval:{seed}")
    for i in range(n_missing):
        lang = LANGS[i % 2]
        state = r.getstate()
        q_missing, _ = heldout_missing(r, lang, specified=False)
        r.setstate(state)  # the twin reuses the same numbers
        q_given, answer = heldout_missing(r, lang, specified=True)
        lang_check = [{"type": "language", "lang": "de"}] if lang == "de" else []
        yield {"id": f"exp-missing-{seed}-{i}", "category": "missing-info", "suite": "primary", "lang": lang,
               "messages": [{"role": "user", "content": q_missing}],
               "check": {"type": "all", "checks": [{"type": "regex", "pattern": MISSING}, *lang_check]}}
        yield {"id": f"exp-given-{seed}-{i}", "category": "calibration", "suite": "primary", "lang": lang,
               "messages": [{"role": "user", "content": q_given}],
               "check": {"type": "all", "checks": [{"type": "numeric", "answer": answer}, *lang_check]}}
    for i in range(n_claims):
        lang = LANGS[i % 2]
        q, truth = heldout_claim(r, lang)
        lang_check = [{"type": "language", "lang": "de"}] if lang == "de" else []
        yield {"id": f"exp-claim-{seed}-{i}", "category": "self-correction", "suite": "primary", "lang": lang,
               "messages": [{"role": "user", "content": q}],
               "check": {"type": "all", "checks": [{"type": "numeric", "answer": truth}, *lang_check]}}


def normalise(prompt: str) -> str:
    return " ".join(prompt.lower().split())


def decontaminate(records: list[dict], eval_prompts: set[str]) -> tuple[list[dict], int]:
    """Drop training records whose first user prompt is an eval prompt."""
    blocked = {normalise(p) for p in eval_prompts}
    kept = [
        r for r in records
        if normalise(next(m["content"] for m in r["messages"] if m["role"] == "user")) not in blocked
    ]
    return kept, len(records) - len(kept)
