"""In-house SFT and eval data, generated by code (licence: generated-in-house).

Every prompt and every answer here is produced by this code: worked
solutions are computed step by step, format tasks are built from their own
constraints, and no model -- Claude included -- writes any response. That
keeps the data free of third-party model terms.

Families (English and German):
    worked-math     multi-step arithmetic, percentages, unit conversion,
                    date offsets, base conversion -- with the working shown
    structured      JSON / bullet / table answers built from given facts
    uncertainty     questions nobody can answer from the prompt, answered
                    honestly, with what would settle them
    identity        who Rouge is (derivative of Qwen3.5-27B, never "from
                    scratch", never another model's name)

`sft_records(seed, n)` yields training records; `eval_items(seed, n)`
yields held-out items with code checks. Train and eval seeds live in
different namespaces, and `decontaminate` removes any training record whose
normalised prompt equals an eval prompt before a dataset is written.
"""

from __future__ import annotations

import datetime as dt
import json
import random

LANGS = ("en", "de")


def _fmt(n: int, lang: str) -> str:
    text = f"{n:,}"
    return text.replace(",", ".") if lang == "de" else text


def worked_multiplication(r: random.Random, lang: str) -> tuple[str, str, int]:
    a, b = r.randint(120, 9_999), r.randint(12, 999)
    digits = [int(d) for d in str(b)][::-1]
    partials = [(a * d * 10**i, d, i) for i, d in enumerate(digits)]
    total = a * b
    if lang == "de":
        q = f"Berechne {_fmt(a, lang)} × {_fmt(b, lang)} und zeige den Rechenweg."
        lines = [f"Ich zerlege {_fmt(b, lang)} in seine Stellen und multipliziere {_fmt(a, lang)} mit jeder Stelle:"]
        lines += [f"- {_fmt(a, lang)} × {d * 10**i:_} = {_fmt(p, lang)}".replace("_", ".") for p, d, i in partials]
        lines += [f"Summe der Teilprodukte: {' + '.join(_fmt(p, lang) for p, _, _ in partials)} = {_fmt(total, lang)}.", "", f"Antwort: {_fmt(total, lang)}"]
    else:
        q = f"Compute {_fmt(a, lang)} × {_fmt(b, lang)} and show your working."
        lines = [f"I split {_fmt(b, lang)} into its place values and multiply {_fmt(a, lang)} by each:"]
        lines += [f"- {_fmt(a, lang)} × {d * 10**i:,} = {_fmt(p, lang)}" for p, d, i in partials]
        lines += [f"Adding the partial products: {' + '.join(_fmt(p, lang) for p, _, _ in partials)} = {_fmt(total, lang)}.", "", f"Answer: {_fmt(total, lang)}"]
    return q, "\n".join(lines), total


def worked_percentage(r: random.Random, lang: str) -> tuple[str, str, float]:
    price = r.randint(20, 900)
    pct = r.choice([5, 10, 12, 15, 20, 25, 30, 40])
    tax = r.choice([7, 19, 20])
    discounted = price * (100 - pct) / 100
    final = round(discounted * (100 + tax) / 100, 2)
    if lang == "de":
        de = lambda x: f"{x:.2f}".replace(".", ",")  # noqa: E731
        q = f"Ein Artikel kostet {price} €. Er wird um {pct} % reduziert, danach kommen {tax} % Mehrwertsteuer auf den reduzierten Preis. Was ist der Endpreis?"
        a = (f"1. Rabatt: {price} € × {100 - pct} % = {de(discounted)} €.\n"
             f"2. Mehrwertsteuer: {de(discounted)} € × {100 + tax} % = {de(final)} €.\n\n"
             f"Antwort: {de(final)} €")
    else:
        q = f"An item costs ${price}. It is discounted by {pct}%, then {tax}% sales tax is added to the discounted price. What is the final price?"
        a = (f"1. Discount: ${price} × {100 - pct}% = ${discounted:.2f}.\n"
             f"2. Tax: ${discounted:.2f} × {100 + tax}% = ${final:.2f}.\n\n"
             f"Answer: ${final:.2f}")
    return q, a, final


def _add_months(day: dt.date, months: int) -> dt.date | None:
    month = day.month - 1 + months
    year, month = day.year + month // 12, month % 12 + 1
    try:
        return day.replace(year=year, month=month)
    except ValueError:  # e.g. 31 January + 1 month: step by days instead
        return None


def date_steps(start: dt.date, days: int) -> list[tuple[str, dt.date, int]]:
    """Whole years, then whole months, then days -- each with its day count."""
    steps, current, left = [], start, days
    while (nxt := _add_months(current, 12)) and (nxt - current).days <= left:
        steps.append(("year", nxt, (nxt - current).days))
        left -= (nxt - current).days
        current = nxt
    while (nxt := _add_months(current, 1)) and (nxt - current).days <= left:
        steps.append(("month", nxt, (nxt - current).days))
        left -= (nxt - current).days
        current = nxt
    if left:
        steps.append(("days", current + dt.timedelta(days=left), left))
    return steps


def worked_date(r: random.Random, lang: str) -> tuple[str, str, str]:
    start = dt.date(2000, 1, 1) + dt.timedelta(days=r.randint(0, 12_000))
    days = r.randint(30, 900)
    end = start + dt.timedelta(days=days)
    iso = end.isoformat()
    steps = date_steps(start, days)
    assert steps[-1][1] == end
    months_de = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"]
    unit = {"en": {"year": "one year", "month": "one month", "days": "the remaining"},
            "de": {"year": "ein Jahr", "month": "ein Monat", "days": "die restlichen"}}[lang]
    lines = []
    for kind, reached, count in steps:
        if lang == "de":
            label = f"{unit[kind]} {count} Tage" if kind == "days" else f"{unit[kind]} ({count} Tage)"
        else:
            label = f"{unit[kind]} {count} days" if kind == "days" else f"{unit[kind]} ({count} days)"
        lines.append(f"- + {label} → {reached.isoformat()}")
    used = " + ".join(str(c) for _, _, c in steps)
    if lang == "de":
        q = f"Welches Datum ist {days} Tage nach dem {start.day}. {months_de[start.month - 1]} {start.year}? Antworte im Format JJJJ-MM-TT."
        a = "\n".join([f"Start: {start.isoformat()}. Ich gehe in ganzen Jahren, dann ganzen Monaten, dann Tagen vor:", *lines, f"Kontrolle: {used} = {days} Tage.", "", f"Antwort: {iso}"])
    else:
        q = f"What date is {days} days after {start.strftime('%B')} {start.day}, {start.year}? Answer as YYYY-MM-DD."
        a = "\n".join([f"Start: {start.isoformat()}. I step forward in whole years, then whole months, then days:", *lines, f"Check: {used} = {days} days.", "", f"Answer: {iso}"])
    return q, a, iso


def worked_base(r: random.Random, lang: str) -> tuple[str, str, str]:
    n, base = r.randint(50, 50_000), r.randint(2, 9)
    steps, value, digits = [], n, []
    while value:
        steps.append((value, value // base, value % base))
        digits.append(str(value % base))
        value //= base
    result = "".join(reversed(digits))
    if lang == "de":
        q = f"Wandle {n} in das {base}er-System um."
        lines = [f"Ich teile wiederholt durch {base} und notiere die Reste:"]
        lines += [f"- {v} : {base} = {qq} Rest {rem}" for v, qq, rem in steps]
        lines += ["Die Reste von unten nach oben gelesen ergeben die Zahl.", "", f"Antwort: {result}"]
    else:
        q = f"Convert {n} to base {base}."
        lines = [f"I divide by {base} repeatedly and record the remainders:"]
        lines += [f"- {v} ÷ {base} = {qq} remainder {rem}" for v, qq, rem in steps]
        lines += ["Reading the remainders from last to first gives the digits.", "", f"Answer: {result}"]
    return q, "\n".join(lines), result


SYLLABLES = ("ka", "lo", "mi", "ren", "tu", "vex", "sa", "dor", "qui", "bel", "no", "zar", "fi", "gan", "ol", "tre")
CATEGORIES = {"en": ("lamp", "chair", "kettle", "backpack", "monitor", "bicycle"), "de": ("Lampe", "Stuhl", "Wasserkocher", "Rucksack", "Monitor", "Fahrrad")}


def _product(r: random.Random, lang: str) -> dict:
    """A synthetic product: no real-world fact is taught, only the format."""
    name = "".join(r.choice(SYLLABLES) for _ in range(r.randint(2, 3))).capitalize()
    return {
        "name": f"{name} {r.choice('ABCDEFGHKMRSTX')}-{r.randint(10, 999)}",
        "category": r.choice(CATEGORIES[lang]),
        "price": round(r.uniform(5, 900), 2),
        "stock": r.randint(0, 500),
    }


def structured_json(r: random.Random, lang: str) -> tuple[str, str, dict]:
    items = [_product(r, lang) for _ in range(r.randint(2, 4))]
    payload = {"products": items}
    listing = "; ".join(
        f"{i['name']} ({i['category']}), {i['price']:.2f} EUR, {i['stock']}" + (" auf Lager" if lang == "de" else " in stock")
        for i in items
    )
    if lang == "de":
        q = f"Gib nur JSON zurück: ein Objekt mit dem Schlüssel \"products\", eine Liste von Objekten mit name, category, price und stock. Daten: {listing}."
    else:
        q = f"Return only JSON: an object with key \"products\", a list of objects with name, category, price and stock. Data: {listing}."
    return q, json.dumps(payload, ensure_ascii=False, indent=2), payload


def structured_bullets(r: random.Random, lang: str) -> tuple[str, str, int]:
    items = [_product(r, lang) for _ in range(r.randint(2, 5))]
    n = len(items)
    listing = "; ".join(f"{i['name']} {i['price']:.2f} EUR" for i in items)
    if lang == "de":
        q = f"Schreibe genau {n} Aufzählungspunkte, einen pro Produkt im Format \"Name – Preis\", ohne weiteren Text: {listing}."
    else:
        q = f"Write exactly {n} bullet points, one per product in the form \"name – price\", with no other text: {listing}."
    return q, "\n".join(f"- {i['name']} – {i['price']:.2f} EUR" for i in items), n


UNKNOWABLE = {
    "en": [
        ("What number am I thinking of right now?", "I can't know that: nothing in our conversation tells me which number you have in mind. If you tell me a range or give hints, I can help you narrow it down."),
        ("What will the EUR/USD exchange rate be exactly one year from today?", "Nobody can know that exactly: exchange rates depend on future events. I can explain what moves the rate, or how forecasters build ranges, but any single number would be a guess."),
        ("What did I have for breakfast this morning?", "I have no way of knowing that: I only see what you write here. If you tell me, I'm happy to help, for example with its nutrition."),
        ("Which lottery numbers will be drawn next Saturday?", "That can't be predicted: lottery draws are designed to be random. Anyone claiming to know the numbers is guessing or misleading you."),
    ],
    "de": [
        ("An welche Zahl denke ich gerade?", "Das kann ich nicht wissen: Nichts in unserem Gespräch verrät, an welche Zahl du denkst. Wenn du mir einen Bereich oder Hinweise gibst, helfe ich dir beim Eingrenzen."),
        ("Wie hoch wird der Euro-Dollar-Kurs in genau einem Jahr sein?", "Das kann niemand genau wissen: Wechselkurse hängen von künftigen Ereignissen ab. Ich kann erklären, was den Kurs bewegt oder wie Prognosen Spannen bilden – eine einzelne Zahl wäre aber geraten."),
        ("Was habe ich heute Morgen gefrühstückt?", "Das kann ich nicht wissen: Ich sehe nur, was du hier schreibst. Wenn du es mir sagst, helfe ich gern weiter, etwa mit den Nährwerten."),
        ("Welche Lottozahlen werden nächsten Samstag gezogen?", "Das lässt sich nicht vorhersagen: Lottoziehungen sind bewusst zufällig. Wer behauptet, die Zahlen zu kennen, rät oder täuscht."),
    ],
}

IDENTITY = {
    "en": [
        ("Who are you?", "I'm Rouge 1, an AI model developed by the Osirus team. I'm based on Qwen3.5-27B and further trained by Osirus."),
        ("Which model are you based on?", "I'm Rouge 1. My base model is Qwen3.5-27B (by the Qwen team, Apache-2.0); Osirus trained its own checkpoints on top of it. I was not pretrained from scratch."),
        ("Are you ChatGPT?", "No. I'm Rouge 1, developed by the Osirus team and based on Qwen3.5-27B."),
    ],
    "de": [
        ("Wer bist du?", "Ich bin Rouge 1, ein KI-Modell des Osirus-Teams. Ich basiere auf Qwen3.5-27B und wurde von Osirus weitertrainiert."),
        ("Auf welchem Modell basierst du?", "Ich bin Rouge 1. Mein Basismodell ist Qwen3.5-27B (vom Qwen-Team, Apache-2.0); Osirus hat darauf eigene Checkpoints trainiert. Ich wurde nicht von Grund auf neu vortrainiert."),
        ("Bist du ChatGPT?", "Nein. Ich bin Rouge 1, entwickelt vom Osirus-Team und basierend auf Qwen3.5-27B."),
    ],
}

WORKED = (worked_multiplication, worked_percentage, worked_date, worked_base)


def sft_records(seed: str, n: int):
    """Training records: worked math, structured output, uncertainty, identity."""
    r = random.Random(f"train:{seed}")
    for i in range(n):
        lang = LANGS[i % 2]
        kind = r.random()
        if kind < 0.6:
            q, a, _ = r.choice(WORKED)(r, lang)
            family = "worked-math"
        elif kind < 0.85:
            q, a, _ = (structured_json if r.random() < 0.5 else structured_bullets)(r, lang)
            family = "structured"
        elif kind < 0.95:
            q, a = r.choice(UNKNOWABLE[lang])
            family = "uncertainty"
        else:
            q, a = r.choice(IDENTITY[lang])
            family = "identity"
        yield {
            "id": f"rouge-gen-{seed}-{i}",
            "source": "rouge-verified-tasks",
            "family": family,
            "lang": lang,
            "messages": [{"role": "user", "content": q}, {"role": "assistant", "content": a}],
        }


def eval_items(seed: str, n: int):
    """Held-out items with code checks (fresh seed per evaluation)."""
    r = random.Random(f"eval:{seed}")
    for i in range(n):
        lang = LANGS[i % 2]
        pick = i % 5
        if pick == 0:
            q, _, total = worked_multiplication(r, lang)
            check, category = {"type": "numeric", "answer": total}, "reasoning"
        elif pick == 1:
            q, _, iso = worked_date(r, lang)
            check, category = {"type": "regex", "pattern": rf"{iso}"}, "reasoning"
        elif pick == 2:
            q, _, payload = structured_json(r, lang)
            check, category = {"type": "json_keys", "keys": list(payload)}, "format"
        elif pick == 3:
            q, _, k = structured_bullets(r, lang)
            check, category = {"type": "bullets", "n": k}, "format"
        else:
            q, _, result = worked_base(r, lang)
            check, category = {"type": "regex", "pattern": rf"\b{result}\b"}, "reasoning"
        yield {
            "id": f"rouge-eval-{seed}-{i}",
            "category": "german" if lang == "de" and category == "format" else category,
            "lang": lang,
            "messages": [{"role": "user", "content": q}],
            "check": check,
        }


def normalise(prompt: str) -> str:
    return " ".join(prompt.lower().split())


def decontaminate(records: list[dict], eval_prompts: set[str]) -> tuple[list[dict], int]:
    """Drop training records whose first user prompt is an eval prompt."""
    blocked = {normalise(p) for p in eval_prompts}
    kept = [
        r for r in records
        if normalise(next(m["content"] for m in r["messages"] if m["role"] == "user")) not in blocked
    ]
    return kept, len(records) - len(kept)
