"""Build the Rouge pretraining corpus: download, clean, deduplicate, split,
check contamination, train or load the tokenizer, tokenize into shards and
write a manifest with the hash of every shard.

    python -m native.data.build --out DIR --tokens 300e6 [--tokenizer tokenizer.json] [--expect manifest.json]

With --expect, the build must reproduce the expected manifest's shard hashes
(a GPU job rebuilding the data proves it trains on exactly the committed
corpus). Deterministic: sources are read in a fixed order at pinned
revisions; every decision is a function of document content.

Per document: NFC normalisation; length and quality filters (alphabetic
ratio, repeated lines); exact dedup (normalised text) and near-dup
fingerprints (normalised head and tail); a hash-based train/validation
split; train documents sharing any word 13-gram with an evaluation text are
dropped (contamination). Upstream sources are already MinHash-deduplicated
(FineWeb, OpenWebMath); the manifest records both.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import random
import re
import tarfile
import time
import unicodedata
import urllib.request
from pathlib import Path

import numpy as np

from . import sources, synth

EOS, BOS, PAD = "<|eos|>", "<|bos|>", "<|pad|>"
SPECIAL = [PAD, BOS, EOS, "<|system|>", "<|user|>", "<|assistant|>", "<|tool|>", "<|image|>", "<|think|>", "<|/think|>"]
CHARS_PER_TOKEN = {"web": 4.2, "math": 3.4, "code": 3.2, "algorithmic": 2.5}
VAL_PER_MILLE = 5
VAL_CAP = 400
SHARD_TOKENS = 64 * 2**20
WORD = re.compile(r"\w+", re.UNICODE)


def sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def normalize(text: str) -> str:
    return unicodedata.normalize("NFC", text).replace("\r\n", "\n").strip()


def quality(text: str, domain: str) -> str | None:
    """None when the document passes, else the reason it is dropped."""
    if domain == "code":
        if len(text) < 200 or len(text) > 200_000:
            return "length"
        if "DO NOT EDIT" in text[:2000] or "autogenerated" in text[:2000].lower():
            return "generated"
        return None
    if len(text) < 200 or len(text) > 400_000:
        return "length"
    letters = sum(c.isalpha() for c in text)
    if letters / len(text) < 0.55:
        return "alpha_ratio"
    lines = [l.strip() for l in text.split("\n") if l.strip()]
    if lines and 1 - len(set(lines)) / len(lines) > 0.3:
        return "repeated_lines"
    return None


def ngrams13(text: str) -> set[int]:
    words = WORD.findall(text.lower())
    return {hash(" ".join(words[i:i + 13])) & 0xFFFFFFFFFFFF for i in range(len(words) - 12)}


# --- sources -----------------------------------------------------------------------
def hf_revision(repo: str) -> str | None:
    try:
        from huggingface_hub import HfApi

        return HfApi().dataset_info(repo).sha
    except Exception:
        return None


def iter_hf(spec: dict, revision: str | None):
    from datasets import load_dataset

    ds = load_dataset(spec["repo"], name=spec["config"], split=spec["split"], streaming=True, revision=revision)
    for i, row in enumerate(ds):
        text = row.get(spec["field"]) or ""
        yield str(row.get("id") or i), text


def iter_code(cache: Path):
    cache.mkdir(parents=True, exist_ok=True)
    for project, tag, url, license_ in sources.CODE:
        path = cache / f"{project}-{tag}.tar.gz"
        if not path.exists():
            with urllib.request.urlopen(url, timeout=300) as r:
                path.write_bytes(r.read())
        with tarfile.open(path, "r:gz") as tar:
            members = sorted((m for m in tar.getmembers() if m.isfile() and m.name.endswith(".py")), key=lambda m: m.name)
            for m in members:
                raw = tar.extractfile(m).read()
                try:
                    text = raw.decode("utf-8")
                except UnicodeDecodeError:
                    continue
                yield f"{project}@{tag}:{m.name.split('/', 1)[-1]}", text, license_


def iter_synth(kind: str):
    for seed in range(10_000):  # evaluation uses seeds >= 10_000 (synth.eval_items)
        yield f"{kind}:{seed}", synth.document(random.Random(f"{kind}:{seed}"), kind)


# --- tokenizer ---------------------------------------------------------------------
def train_tokenizer(texts, vocab: int, path: Path) -> None:
    from tokenizers import Tokenizer, decoders, models, normalizers, pre_tokenizers, trainers

    tok = Tokenizer(models.BPE(byte_fallback=False))
    tok.normalizer = normalizers.NFC()
    tok.pre_tokenizer = pre_tokenizers.ByteLevel(add_prefix_space=False)
    tok.decoder = decoders.ByteLevel()
    trainer = trainers.BpeTrainer(vocab_size=vocab, special_tokens=SPECIAL, min_frequency=2,
                                  initial_alphabet=pre_tokenizers.ByteLevel.alphabet(), show_progress=False)
    tok.train_from_iterator(texts, trainer=trainer)
    tok.save(str(path))


def load_tokenizer(path: Path):
    from tokenizers import Tokenizer

    return Tokenizer.from_file(str(path))


# --- build -------------------------------------------------------------------------
def collect(out: Path, total_tokens: float, mixture: dict, cache: Path, revisions: dict) -> dict:
    """Documents per source and split, after cleaning, dedup and split. Returns {source: {...}}."""
    result = {}
    for name, share in mixture.items():
        if name in sources.HF:
            spec, license_ = sources.HF[name], sources.HF[name]["license"]
            domain = spec["domain"]
            docs = ((i, t, license_) for i, t in iter_hf(spec, revisions.get(name)))
        elif name == "code_py":
            domain, docs = "code", iter_code(cache)
        else:
            domain = sources.SYNTHETIC[name]["domain"]
            docs = ((i, t, "generated") for i, t in iter_synth(name))
        budget_chars = total_tokens * share * CHARS_PER_TOKEN[domain] * 1.08
        seen, fingerprints = set(), set()
        train, val, dropped, chars, n = [], [], {}, 0, 0
        for doc_id, text, license_ in docs:
            n += 1
            text = normalize(text)
            reason = None if name in sources.SYNTHETIC else quality(text, domain)  # generated text is not web text
            key = sha(" ".join(text.lower().split()))
            fp = sha(text[:256] + "\x00" + text[-256:])
            if reason is None and key in seen:
                reason = "exact_dup"
            if reason is None and fp in fingerprints:
                reason = "near_dup"
            if reason:
                dropped[reason] = dropped.get(reason, 0) + 1
                continue
            seen.add(key)
            fingerprints.add(fp)
            is_val = int(key[:8], 16) % 1000 < VAL_PER_MILLE and len(val) < VAL_CAP and domain != "algorithmic"
            (val if is_val else train).append((doc_id, text, license_))
            if not is_val:
                chars += len(text)
                if chars >= budget_chars:
                    break
        result[name] = {"domain": domain, "train": train, "val": val, "docs_seen": n, "dropped": dropped,
                        "license": sorted({l for _, _, l in train}) or ["generated"], "revision": revisions.get(name)}
        print(f"[data] {name}: {n} seen, {len(train)} train, {len(val)} val, dropped {dropped}", flush=True)
    return result


def decontaminate(corpus: dict) -> dict:
    eval_grams: set[int] = set()
    for src in corpus.values():
        for _, text, _ in src["val"]:
            eval_grams |= ngrams13(text)
    for kind in ("math_synth", "algo_synth"):
        for prompt, answer in synth.eval_items(kind, 500):
            eval_grams |= ngrams13(f"{prompt} {answer}")
    report = {}
    for name, src in corpus.items():
        keep = [d for d in src["train"] if not (ngrams13(d[1]) & eval_grams)]
        report[name] = len(src["train"]) - len(keep)
        src["train"] = keep
    return report


def write_shards(corpus: dict, tok, out: Path, total_tokens: float, mixture: dict) -> dict:
    eos = tok.token_to_id(EOS)
    dtype = np.uint16 if tok.get_vocab_size() <= 65535 else np.uint32
    shards = {}
    for name, src in corpus.items():
        for split in ("train", "val"):
            docs = src[split]
            budget = int(total_tokens * mixture[name]) if split == "train" else None
            ids, written, idx = [], 0, 0
            files = []

            def flush(final=False):
                nonlocal ids, idx
                if not ids or (not final and sum(len(x) for x in ids) < SHARD_TOKENS):
                    return
                arr = np.concatenate(ids).astype(dtype)
                path = out / split / f"{name}_{idx:04d}.bin"
                path.parent.mkdir(parents=True, exist_ok=True)
                arr.tofile(path)
                files.append({"path": f"{split}/{path.name}", "tokens": int(arr.size),
                              "sha256": hashlib.sha256(arr.tobytes()).hexdigest()})
                ids, idx = [], idx + 1

            for s in range(0, len(docs), 512):
                batch = tok.encode_batch([d[1] for d in docs[s:s + 512]])
                for enc in batch:
                    piece = np.asarray(enc.ids + [eos], dtype=np.int64)
                    if budget is not None and written + piece.size > budget:
                        piece = piece[:budget - written]
                    ids.append(piece)
                    written += piece.size
                    if budget is not None and written >= budget:
                        break
                flush()
                if budget is not None and written >= budget:
                    break
            flush(final=True)
            entry = {"tokens": written, "files": files}
            if split == "val":  # bits per byte need the bytes behind the validation tokens
                entry["bytes"] = sum(len(d[1].encode("utf-8")) + 1 for d in docs)
            shards.setdefault(name, {})[split] = entry
    return shards


def build(out: Path, total_tokens: float, mixture: dict, tokenizer: Path | None, vocab: int, expect: dict | None) -> dict:
    out.mkdir(parents=True, exist_ok=True)
    start = time.time()
    revisions = (expect or {}).get("revisions") or {n: hf_revision(sources.HF[n]["repo"]) for n in mixture if n in sources.HF}
    corpus = collect(out, total_tokens, mixture, out / "cache", revisions)
    contamination = decontaminate(corpus)
    tok_path = out / "tokenizer.json"
    if tokenizer:
        tok_path.write_bytes(Path(tokenizer).read_bytes())
    else:
        rng = random.Random("tokenizer-sample")
        sample = [d[1] for src in corpus.values() for d in src["train"] if rng.random() < 0.25]
        train_tokenizer(sample, vocab, tok_path)
    tok = load_tokenizer(tok_path)
    shards = write_shards(corpus, tok, out, total_tokens, mixture)
    manifest = {
        "schema": "rouge.data/1",
        "created_s": round(time.time() - start, 1),
        "mixture": mixture, "total_tokens": int(total_tokens), "revisions": revisions,
        "tokenizer": {"sha256": hashlib.sha256(tok_path.read_bytes()).hexdigest(), "vocab": tok.get_vocab_size(),
                      "special": SPECIAL},
        "sources": {n: {"domain": s["domain"], "license": s["license"], "revision": s["revision"], "docs_seen": s["docs_seen"],
                        "docs_train": len(s["train"]), "docs_val": len(s["val"]), "dropped": s["dropped"],
                        "contaminated_dropped": contamination[n], "shards": shards[n]}
                    for n, s in corpus.items()},
        "dedup": "exact (normalised text) + near-dup fingerprint (head/tail) in-house; upstream MinHash for FineWeb-Edu, FineWeb-2, OpenWebMath",
        "contamination": "train documents sharing any word 13-gram with validation documents or generated eval items are dropped",
        "code_sha": os.environ.get("GITHUB_SHA", "local"),
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=1))
    if expect:
        mismatch = [(n, sp) for n, s in expect["sources"].items() for sp in ("train", "val")
                    if [f["sha256"] for f in s["shards"][sp]["files"]] != [f["sha256"] for f in manifest["sources"][n]["shards"][sp]["files"]]]
        if mismatch or expect["tokenizer"]["sha256"] != manifest["tokenizer"]["sha256"]:
            raise SystemExit(f"rebuild does not reproduce the expected corpus: {mismatch or 'tokenizer'}")
        print("[data] rebuild reproduces every expected shard hash", flush=True)
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    parser.add_argument("--tokens", type=float, default=300e6)
    parser.add_argument("--vocab", type=int, default=32768)
    parser.add_argument("--tokenizer")
    parser.add_argument("--expect")
    parser.add_argument("--mixture", default="v1")
    parser.add_argument("--only", nargs="*", help="restrict to these sources (tests)")
    args = parser.parse_args()
    mixture = dict(sources.MIXTURE_V1)
    if args.only:
        mixture = {k: v / sum(mixture[x] for x in args.only) for k, v in mixture.items() if k in args.only}
    expect = json.loads(Path(args.expect).read_text()) if args.expect else None
    manifest = build(Path(args.out), args.tokens, mixture, Path(args.tokenizer) if args.tokenizer else None, args.vocab, expect)
    print(json.dumps({n: s["shards"]["train"]["tokens"] for n, s in manifest["sources"].items()}))


if __name__ == "__main__":
    main()
