"""Build the Rouge pretraining corpus: download, clean, deduplicate, split,
check contamination, train or load the tokenizer, tokenize into shards and
write a manifest with the hash of every shard.

    python -m native.data.build --out DIR --tokens 300e6 [--tokenizer tokenizer.json] [--expect manifest.json]

With --expect, the build must reproduce the expected manifest's shard hashes
(a GPU job rebuilding the data proves it trains on exactly the committed
corpus). Deterministic: sources are read in a fixed order at pinned
revisions; every decision is a function of document content.

Per document: NFC normalisation; length and quality filters (alphabetic
ratio, repeated lines); exact dedup (normalised text) and near-dup
fingerprints (normalised head and tail); a hash-based train/validation
split; train documents sharing any word 13-gram with an evaluation text are
dropped (contamination). Upstream sources are already MinHash-deduplicated
(FineWeb, OpenWebMath); the manifest records both.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import multiprocessing
import os
import random
import re
import resource
import shutil
import tarfile
import time
import unicodedata
import urllib.request
import zlib
from pathlib import Path

import numpy as np

from . import sources, synth

EOS, BOS, PAD = "<|eos|>", "<|bos|>", "<|pad|>"
SPECIAL = [PAD, BOS, EOS, "<|system|>", "<|user|>", "<|assistant|>", "<|tool|>", "<|image|>", "<|think|>", "<|/think|>"]
CHARS_PER_TOKEN = {"web": 4.2, "math": 3.4, "code": 3.2, "algorithmic": 2.5}
VAL_PER_MILLE = 5
VAL_CAP = 400
SHARD_TOKENS = 64 * 2**20
TOKENIZER_SAMPLE_CHARS = 400_000_000   # BPE training sample cap (stratified: 25% of documents per source)
WORD = re.compile(r"\w+", re.UNICODE)


def sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def normalize(text: str) -> str:
    return unicodedata.normalize("NFC", text).replace("\r\n", "\n").strip()


def quality(text: str, domain: str) -> str | None:
    """None when the document passes, else the reason it is dropped."""
    if domain == "code":
        if len(text) < 200 or len(text) > 200_000:
            return "length"
        if "DO NOT EDIT" in text[:2000] or "autogenerated" in text[:2000].lower():
            return "generated"
        return None
    if len(text) < 200 or len(text) > 400_000:
        return "length"
    letters = sum(c.isalpha() for c in text)
    if letters / len(text) < 0.55:
        return "alpha_ratio"
    lines = [l.strip() for l in text.split("\n") if l.strip()]
    if lines and 1 - len(set(lines)) / len(lines) > 0.3:
        return "repeated_lines"
    return None


def stable_hash(text: str) -> int:
    """64-bit hash that is identical in every process (Python's hash() is salted per process)."""
    b = text.encode("utf-8")
    return (zlib.crc32(b) << 32) | zlib.adler32(b)


def ngrams13(text: str) -> set[int]:
    words = WORD.findall(text.lower())
    return {stable_hash(" ".join(words[i:i + 13])) for i in range(len(words) - 12)}


# --- sources -----------------------------------------------------------------------
def hf_revision(repo: str) -> str | None:
    try:
        from huggingface_hub import HfApi

        return HfApi().dataset_info(repo).sha
    except Exception:
        return None


def iter_hf(spec: dict, revision: str | None):
    from datasets import load_dataset

    ds = load_dataset(spec["repo"], name=spec["config"], split=spec["split"], streaming=True, revision=revision)
    for i, row in enumerate(ds):
        text = row.get(spec["field"]) or ""
        yield str(row.get("id") or i), text


MISSING_CODE: list[str] = []


def iter_code(cache: Path, code_set: str = "v1"):
    cache.mkdir(parents=True, exist_ok=True)
    for project, tag, url, license_ in sources.CODE_SETS[code_set]:
        path = cache / f"{project}-{tag}.tar.gz"
        if not path.exists():
            try:
                with urllib.request.urlopen(url, timeout=600) as r:
                    path.write_bytes(r.read())
            except Exception as e:  # recorded in the manifest; a rebuild must see the same set
                MISSING_CODE.append(f"{project}@{tag}: {type(e).__name__}")
                print(f"[data] code archive unavailable: {project}@{tag} ({type(e).__name__})", flush=True)
                continue
        with tarfile.open(path, "r:gz") as tar:
            members = sorted((m for m in tar.getmembers() if m.isfile() and m.name.endswith(".py")), key=lambda m: m.name)
            for m in members:
                raw = tar.extractfile(m).read()
                try:
                    text = raw.decode("utf-8")
                except UnicodeDecodeError:
                    continue
                yield f"{project}@{tag}:{m.name.split('/', 1)[-1]}", text, license_


def iter_synth(kind: str):
    """Generated documents; items whose prompt is an evaluation prompt are never emitted (exact-match decontamination:
    these prompts are shorter than 13 words, so the n-gram check cannot see them)."""
    held_out = {p for p, _ in synth.eval_items(kind, 2000)}
    for seed in range(200_000):  # training RNG namespace "<kind>:<seed>"; evaluation uses "<kind>:eval:<seed>"
        yield f"{kind}:{seed}", synth.document(random.Random(f"{kind}:{seed}"), kind, exclude=held_out)


# --- tokenizer ---------------------------------------------------------------------
def train_tokenizer(texts, vocab: int, path: Path) -> None:
    from tokenizers import Tokenizer, decoders, models, normalizers, pre_tokenizers, trainers

    tok = Tokenizer(models.BPE(byte_fallback=False))
    tok.normalizer = normalizers.NFC()
    tok.pre_tokenizer = pre_tokenizers.ByteLevel(add_prefix_space=False)
    tok.decoder = decoders.ByteLevel()
    trainer = trainers.BpeTrainer(vocab_size=vocab, special_tokens=SPECIAL, min_frequency=2,
                                  initial_alphabet=pre_tokenizers.ByteLevel.alphabet(), show_progress=False)
    tok.train_from_iterator(texts, trainer=trainer)
    tok.save(str(path))


def load_tokenizer(path: Path):
    from tokenizers import Tokenizer

    return Tokenizer.from_file(str(path))


# --- build -------------------------------------------------------------------------
class DocFile:
    """Training documents of one source, spilled to disk as JSON lines in arrival order.

    A 2B-token corpus holds about 9 GB of text, more than a GitHub runner's memory; lists
    of documents are kept only for validation splits (at most VAL_CAP per source).
    """

    def __init__(self, path: Path):
        path.parent.mkdir(parents=True, exist_ok=True)
        self.path, self.count, self.chars, self.licenses = path, 0, 0, set()
        self._f = open(path, "w", encoding="utf-8")

    def append(self, doc: tuple) -> None:
        self._f.write(json.dumps(doc, ensure_ascii=False) + "\n")
        self.count += 1
        self.chars += len(doc[1])
        self.licenses.add(doc[2])

    def close(self) -> None:
        if self._f is not None:
            self._f.close()
            self._f = None

    def __len__(self) -> int:
        return self.count

    def __iter__(self):
        self.close()
        with open(self.path, encoding="utf-8") as f:
            for line in f:
                yield tuple(json.loads(line))


def batched(docs, n: int):
    chunk = []
    for d in docs:
        chunk.append(d)
        if len(chunk) == n:
            yield chunk
            chunk = []
    if chunk:
        yield chunk


def peak_rss(stage: str) -> None:
    print(f"[data] {stage}: peak memory {resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 2**20:.2f} GB", flush=True)


def collect(out: Path, total_tokens: float, mixture: dict, cache: Path, revisions: dict, code_set: str = "v1") -> dict:
    """Documents per source and split, after cleaning, dedup and split. Returns {source: {...}}."""
    result = {}
    for name, share in mixture.items():
        if name in sources.HF:
            spec, license_ = sources.HF[name], sources.HF[name]["license"]
            domain = spec["domain"]
            docs = ((i, t, license_) for i, t in iter_hf(spec, revisions.get(name)))
        elif name == "code_py":
            domain, docs = "code", iter_code(cache, code_set)
        else:
            domain = sources.SYNTHETIC[name]["domain"]
            docs = ((i, t, "generated") for i, t in iter_synth(name))
        budget_chars = total_tokens * share * CHARS_PER_TOKEN[domain] * 1.08
        seen, fingerprints = set(), set()
        train, val, dropped, chars, n = DocFile(out / "tmp" / f"{name}.train.jsonl"), [], {}, 0, 0
        for doc_id, text, license_ in docs:
            n += 1
            text = normalize(text)
            reason = None if name in sources.SYNTHETIC else quality(text, domain)  # generated text is not web text
            key = sha(" ".join(text.lower().split()))
            fp = sha(text[:256] + "\x00" + text[-256:])
            if reason is None and key in seen:
                reason = "exact_dup"
            if reason is None and fp in fingerprints:
                reason = "near_dup"
            if reason:
                dropped[reason] = dropped.get(reason, 0) + 1
                continue
            seen.add(key)
            fingerprints.add(fp)
            is_val = int(key[:8], 16) % 1000 < VAL_PER_MILLE and len(val) < VAL_CAP and domain != "algorithmic"
            (val if is_val else train).append((doc_id, text, license_))
            if not is_val:
                chars += len(text)
                if chars >= budget_chars:
                    break
        train.close()
        result[name] = {"domain": domain, "train": train, "val": val, "docs_seen": n, "dropped": dropped,
                        "license": sorted(train.licenses) or ["generated"], "revision": revisions.get(name)}
        print(f"[data] {name}: {n} seen, {len(train)} train, {len(val)} val, dropped {dropped}", flush=True)
    return result


_EVAL_GRAMS: set[int] = set()


def _contaminated(text: str) -> bool:
    words = WORD.findall(text.lower())
    return any(stable_hash(" ".join(words[i:i + 13])) in _EVAL_GRAMS for i in range(len(words) - 12))


def decontaminate(corpus: dict) -> dict:
    """Drop train documents sharing a word 13-gram with any evaluation text (parallel over documents).

    The n-gram hash is stable across processes, so a decision depends only on
    document content and a rebuild reproduces it exactly.
    """
    global _EVAL_GRAMS
    eval_grams: set[int] = set()
    for src in corpus.values():
        for _, text, _ in src["val"]:
            eval_grams |= ngrams13(text)
    for kind in ("math_synth", "algo_synth"):
        for prompt, answer in synth.eval_items(kind, 500):
            eval_grams |= ngrams13(f"{prompt} {answer}")
    _EVAL_GRAMS = eval_grams
    report = {}
    with multiprocessing.get_context("fork").Pool(os.cpu_count() or 1) as pool:
        for name, src in corpus.items():
            kept, dropped = DocFile(src["train"].path.with_suffix(".kept.jsonl")), 0
            for chunk in batched(src["train"], 16384):   # bounded memory; order and decisions unchanged
                flags = pool.map(_contaminated, [d[1] for d in chunk], chunksize=64)
                for d, bad in zip(chunk, flags):
                    if bad:
                        dropped += 1
                    else:
                        kept.append(d)
            kept.close()
            src["train"].path.unlink()
            report[name], src["train"] = dropped, kept
    return report


def write_shards(corpus: dict, tok, out: Path, total_tokens: float, mixture: dict) -> dict:
    eos = tok.token_to_id(EOS)
    dtype = np.uint16 if tok.get_vocab_size() <= 65535 else np.uint32
    shards = {}
    for name, src in corpus.items():
        for split in ("train", "val"):
            docs = src[split]
            budget = int(total_tokens * mixture[name]) if split == "train" else None
            ids, written, idx = [], 0, 0
            files = []

            def flush(final=False):
                nonlocal ids, idx
                if not ids or (not final and sum(len(x) for x in ids) < SHARD_TOKENS):
                    return
                arr = np.concatenate(ids).astype(dtype)
                path = out / split / f"{name}_{idx:04d}.bin"
                path.parent.mkdir(parents=True, exist_ok=True)
                arr.tofile(path)
                files.append({"path": f"{split}/{path.name}", "tokens": int(arr.size),
                              "sha256": hashlib.sha256(arr.tobytes()).hexdigest()})
                ids, idx = [], idx + 1

            for chunk in batched(docs, 512):
                batch = tok.encode_batch([d[1] for d in chunk])
                for enc in batch:
                    piece = np.asarray(enc.ids + [eos], dtype=np.int64)
                    if budget is not None and written + piece.size > budget:
                        piece = piece[:budget - written]
                    ids.append(piece)
                    written += piece.size
                    if budget is not None and written >= budget:
                        break
                flush()
                if budget is not None and written >= budget:
                    break
            flush(final=True)
            entry = {"tokens": written, "files": files}
            if split == "val":  # bits per byte need the bytes behind the validation tokens
                entry["bytes"] = sum(len(d[1].encode("utf-8")) + 1 for d in docs)
            shards.setdefault(name, {})[split] = entry
    return shards


def src_share(src: dict, corpus: dict) -> float:
    """Share of a source in the tokenizer sample: its share of training characters."""
    total = sum(s["train"].chars for s in corpus.values()) or 1
    return src["train"].chars / total


def build(out: Path, total_tokens: float, mixture: dict, tokenizer: Path | None, vocab: int, expect: dict | None,
          mixture_name: str = "v1") -> dict:
    out.mkdir(parents=True, exist_ok=True)
    start = time.time()
    revisions = (expect or {}).get("revisions") or {n: hf_revision(sources.HF[n]["repo"]) for n in mixture if n in sources.HF}
    code_set = (expect or {}).get("code_set") or mixture_name
    corpus = collect(out, total_tokens, mixture, out / "cache", revisions, code_set)
    peak_rss("collected")
    contamination = decontaminate(corpus)
    peak_rss("decontaminated")
    tok_path = out / "tokenizer.json"
    if tokenizer:
        tok_path.write_bytes(Path(tokenizer).read_bytes())
    else:
        rng, sample, chars = random.Random("tokenizer-sample"), [], 0
        for src in corpus.values():
            cap = TOKENIZER_SAMPLE_CHARS * src_share(src, corpus)
            taken = 0
            for d in src["train"]:
                if rng.random() < 0.25 and taken < cap:
                    sample.append(d[1])
                    taken += len(d[1])
            chars += taken
        print(f"[data] tokenizer sample: {len(sample)} documents, {chars / 1e6:.0f}M characters", flush=True)
        train_tokenizer(sample, vocab, tok_path)
    tok = load_tokenizer(tok_path)
    shards = write_shards(corpus, tok, out, total_tokens, mixture)
    peak_rss("tokenized")
    shutil.rmtree(out / "tmp", ignore_errors=True)   # spilled documents are not part of the corpus
    manifest = {
        "schema": "rouge.data/1",
        "created_s": round(time.time() - start, 1),
        "mixture": mixture, "total_tokens": int(total_tokens), "revisions": revisions,
        "code_set": code_set, "code_projects": [f"{p}@{t} ({l})" for p, t, _, l in sources.CODE_SETS[code_set]],
        "code_missing": MISSING_CODE,
        "tokenizer": {"sha256": hashlib.sha256(tok_path.read_bytes()).hexdigest(), "vocab": tok.get_vocab_size(),
                      "special": SPECIAL},
        "sources": {n: {"domain": s["domain"], "license": s["license"], "revision": s["revision"], "docs_seen": s["docs_seen"],
                        "docs_train": len(s["train"]), "docs_val": len(s["val"]), "dropped": s["dropped"],
                        "contaminated_dropped": contamination[n], "shards": shards[n]}
                    for n, s in corpus.items()},
        "dedup": "exact (normalised text) + near-dup fingerprint (head/tail) in-house; upstream MinHash for FineWeb-Edu, FineWeb-2, OpenWebMath",
        "contamination": "train documents sharing any word 13-gram with validation documents or generated eval items are dropped",
        "code_sha": os.environ.get("GITHUB_SHA", "local"),
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=1))
    if expect:
        mismatch = [(n, sp) for n, s in expect["sources"].items() for sp in ("train", "val")
                    if [f["sha256"] for f in s["shards"][sp]["files"]] != [f["sha256"] for f in manifest["sources"][n]["shards"][sp]["files"]]]
        if mismatch or expect["tokenizer"]["sha256"] != manifest["tokenizer"]["sha256"]:
            raise SystemExit(f"rebuild does not reproduce the expected corpus: {mismatch or 'tokenizer'}")
        print("[data] rebuild reproduces every expected shard hash", flush=True)
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    parser.add_argument("--tokens", type=float, default=300e6)
    parser.add_argument("--vocab", type=int, default=32768)
    parser.add_argument("--tokenizer")
    parser.add_argument("--expect")
    parser.add_argument("--mixture", default="v1")
    parser.add_argument("--only", nargs="*", help="restrict to these sources (tests)")
    args = parser.parse_args()
    mixture = dict(sources.MIXTURES[args.mixture])
    if args.only:
        mixture = {k: v / sum(mixture[x] for x in args.only) for k, v in mixture.items() if k in args.only}
    expect = json.loads(Path(args.expect).read_text()) if args.expect else None
    tokens = args.tokens
    if expect:  # a rebuild takes the expected corpus's size and mixture
        tokens, mixture = expect["total_tokens"], expect["mixture"]
    manifest = build(Path(args.out), tokens, mixture, Path(args.tokenizer) if args.tokenizer else None, args.vocab, expect,
                     mixture_name=args.mixture)
    print(json.dumps({n: s["shards"]["train"]["tokens"] for n, s in manifest["sources"].items()}))


if __name__ == "__main__":
    main()
